using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DroneDash_x64.Desktop.SmartFarming.LocalProcessing;

public static class LocalProcessingPlanExporter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter() }
    };

    public static (string JsonPath, string ScriptPath, string ReadmePath) Export(
        LocalProcessingPlan plan)
    {
        Directory.CreateDirectory(plan.Workspace);
        Directory.CreateDirectory(Path.Combine(plan.Workspace, "registration"));
        Directory.CreateDirectory(Path.Combine(plan.Workspace, "registered"));
        Directory.CreateDirectory(Path.Combine(plan.Workspace, "corrected"));
        Directory.CreateDirectory(Path.Combine(plan.Workspace, "indices"));

        foreach (var step in plan.Steps)
        {
            if (string.IsNullOrWhiteSpace(step.OutputPath))
                continue;

            var outputDirectory =
                Path.GetDirectoryName(
                    Path.GetFullPath(step.OutputPath));

            if (!string.IsNullOrWhiteSpace(outputDirectory))
                Directory.CreateDirectory(outputDirectory);
        }

        var jsonPath = Path.Combine(
            plan.Workspace,
            "local-processing-plan.json");

        var scriptPath = Path.Combine(
            plan.Workspace,
            "run-smart-farming-processing.ps1");

        var readmePath = Path.Combine(
            plan.Workspace,
            "README.txt");

        File.WriteAllText(
            jsonPath,
            JsonSerializer.Serialize(plan, JsonOptions),
            new UTF8Encoding(false));

        File.WriteAllText(
            scriptPath,
            BuildPowerShell(plan),
            new UTF8Encoding(false));

        var readme = new StringBuilder();
        readme.AppendLine("DroneDash Smart Farming - local processing workspace");
        readme.AppendLine();
        readme.AppendLine($"Capture: {plan.CaptureKey}");
        readme.AppendLine($"Created: {plan.CreatedAtUtc:O}");
        readme.AppendLine();
        readme.AppendLine("Warnings:");
        foreach (var warning in plan.Warnings)
            readme.AppendLine("- " + warning);

        readme.AppendLine();
        readme.AppendLine("Review local-processing-plan.json and the generated PowerShell script before execution.");
        readme.AppendLine("The source M3M files are read-only inputs; outputs stay inside this workspace.");

        File.WriteAllText(
            readmePath,
            readme.ToString(),
            new UTF8Encoding(false));

        return (jsonPath, scriptPath, readmePath);
    }

    private static string BuildPowerShell(LocalProcessingPlan plan)
    {
        var builder = new StringBuilder();
        builder.AppendLine("$ErrorActionPreference = 'Stop'");
        builder.AppendLine("Set-StrictMode -Version Latest");
        builder.AppendLine();
        builder.AppendLine($"# Capture: {EscapeComment(plan.CaptureKey)}");
        builder.AppendLine("# Generated by DroneDash_x64. Review before running.");
        builder.AppendLine();

        foreach (var step in plan.Steps)
        {
            builder.AppendLine($"Write-Host {PsQuote($"[{step.Id}] {step.Description}")}");
            builder.Append("& ");
            builder.Append(PsQuote(step.Program));

            foreach (var argument in step.Arguments)
            {
                builder.Append(' ');
                builder.Append(PsQuote(argument));
            }

            builder.AppendLine();
            builder.AppendLine("if ($LASTEXITCODE -ne 0) { throw 'Processing step failed.' }");
            builder.AppendLine();
        }

        builder.AppendLine("Write-Host 'Smart Farming local processing completed.'");
        return builder.ToString();
    }

    private static string PsQuote(string value) =>
        "'" + value.Replace("'", "''") + "'";

    private static string EscapeComment(string value) =>
        value.Replace("\r", " ").Replace("\n", " ");
}
